-- Abre Supabase Dashboard -> SQL Editor -> New Query
-- Pega este código completo y dale al botón verde "Run"

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT,
  role TEXT DEFAULT 'user',
  google_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  currency TEXT DEFAULT 'USD',
  stock INTEGER DEFAULT 0,
  images JSONB DEFAULT '[]'::jsonb,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- IMPORTANTE: No insertes usuarios con contraseñas hardcodeadas aquí.
-- Genera tu propio hash bcrypt y crea el usuario admin de forma segura, por ejemplo:
--
--   node -e "console.log(require('bcryptjs').hashSync('TU_PASSWORD_REAL', 12))"
--
-- Copia el hash resultante y ejecuta un INSERT manual sólo tú, con tu correo real:
--
--   INSERT INTO public.users (email, password, role)
--   VALUES ('tu_correo_admin@ejemplo.com', '<hash_generado>', 'admin')
--   ON CONFLICT (email) DO NOTHING;
--
-- No documentes contraseñas en texto plano ni las subas a git.
