-- Abre Supabase Dashboard -> SQL Editor -> New Query
-- Pega este código completo y dale al botón verde "Run"

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT,
  role TEXT DEFAULT 'user',
  google_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  currency TEXT DEFAULT 'USD',
  stock INTEGER DEFAULT 0,
  images JSONB DEFAULT '[]'::jsonb,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insertar usuarios por defecto (las contraseñas están hasheadas con bcrypt)
-- 'leo.barrantes8@gmail.com' -> TestUser#123
-- 'lbarrantesm@ucenfotec.ac.cr' -> TestAdmin#123

INSERT INTO public.users (email, password, role)
VALUES 
  ('leobarrantes8@gmail.com', '$2a$10$wJt0d5mK/7q.d7m/pWqD1uGXXdK9x6R6rZQy7I/hJ1R/cTfQO5wzS', 'user'),
  ('lbarrantesm@ucenfotec.ac.cr', '$2a$10$tZ2yN/hX2QzKx2g9O8L8jOx31Q3p/wQx4r3t0m1Q/eR4T5e6X7Y8Z', 'admin')
ON CONFLICT (email) DO NOTHING;
